In [1]:
import pylaeoclim_leeds.hadcm3_processing as hcm3
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import pylaeoclim_leeds.util_hadcm3 as util
import pylaeoclim_leeds.zones as zones
import time
import cftime
import netCDF4

# DEMO performance

Should Clear carray cache to be more accurate!

## Parallel computing

### On OCNRDS

In [21]:
array = xr.open_dataset("~/database/xosfy/time_series/xosfy.merid.annual.nc", chunks=10).Merid_Atlantic
array

<xarray.DataArray 'Merid_Atlantic' (t: 99, depth: 21, latitude: 143)>
dask.array<open_dataset-4b2a7b412df59046b7ea4df533a408fcMerid_Atlantic, shape=(99, 21, 143), dtype=float32, chunksize=(10, 10, 10), chunktype=numpy.ndarray>
Coordinates:
  * depth     (depth) float32 0.0 10.0 20.0 30.0 ... 4269.5 4884.8 5500.0996
  * latitude  (latitude) float32 -88.75 -87.5 -86.25 -85.0 ... 86.25 87.5 88.75
  * t         (t) object 0101-06-01 00:00:00 ... 0199-06-01 00:00:00
Attributes:
    long_name:  Meridional Overturning Stream Function (Atlantic)
    units:      Sv

In [22]:
array.load()
array

<xarray.DataArray 'Merid_Atlantic' (t: 99, depth: 21, latitude: 143)>
array([[[            nan,             nan,             nan, ...,
          0.00000000e+00,  0.00000000e+00,             nan],
        [            nan,             nan,             nan, ...,
          3.56527716e-02,  1.58703905e-02,             nan],
        [            nan,             nan,             nan, ...,
          3.72115448e-02,  1.60543919e-02,             nan],
        ...,
        [            nan,             nan,             nan, ...,
          1.21071935e-08, -8.71941447e-04,             nan],
        [            nan,             nan,             nan, ...,
                     nan,  2.27591954e-08,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       [[            nan,             nan,             nan, ...,
          0.00000000e+00,  0.00000000e+00,             nan],
        [            nan,             nan,             nan, ...,
          2.21869797e-02,  1.12919295e-02,             nan],
        [            nan,             nan,             nan, ...,
          3.65088582e-02,  1.57182179e-02,             nan],
        ...,
        [            nan,             nan,             nan, ...,
          9.08039510e-08, -2.57306919e-03,             nan],
        [            nan,             nan,             nan, ...,
                     nan, -3.25962901e-08,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       [[            nan,             nan,             nan, ...,
          0.00000000e+00,  0.00000000e+00,             nan],
        [            nan,             nan,             nan, ...,
          4.14799415e-02,  2.11797077e-02,             nan],
        [            nan,             nan,             nan, ...,
          4.44747768e-02,  2.18667891e-02,             nan],
        ...,
        [            nan,             nan,             nan, ...,
         -6.14672899e-08, -1.32671278e-02,             nan],
        [            nan,             nan,             nan, ...,
                     nan,  7.26431608e-08,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       ...,

       [[            nan,             nan,             nan, ...,
          0.00000000e+00,  0.00000000e+00,             nan],
        [            nan,             nan,             nan, ...,
          8.51093698e-03,  9.75363888e-03,             nan],
        [            nan,             nan,             nan, ...,
         -1.17185852e-02, -1.71550363e-03,             nan],
        ...,
        [            nan,             nan,             nan, ...,
         -7.45058060e-08, -4.07755375e-03,             nan],
        [            nan,             nan,             nan, ...,
                     nan,  1.95577741e-08,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       [[            nan,             nan,             nan, ...,
          0.00000000e+00,  0.00000000e+00,             nan],
        [            nan,             nan,             nan, ...,
          8.39274749e-03,  6.95278775e-03,             nan],
        [            nan,             nan,             nan, ...,
          5.03350282e-03,  5.17862383e-03,             nan],
        ...,
        [            nan,             nan,             nan, ...,
          2.98023224e-08, -1.66621208e-02,             nan],
        [            nan,             nan,             nan, ...,
                     nan,  3.16649675e-08,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       [[            nan,             nan,             nan, ..

In [13]:
print("test")
if False : print("test2")
print("test3")

test
test3


In [9]:
start = time.time()
ds = hcm3.OCNYDS("xoupa", 1, 1000, chunks=100)
temperature = ds.temperature(mode_lat="weighted_mean", mode_lon="weighted_mean", mode_z="weighted_mean")
print(temperature)
print(temperature.values())
print(f"With chunks : {time.time() - start}")

__ Importing <class 'pylaeoclim_leeds.hadcm3_processing.OCNYDS'>
____ Paths generated for xoupa between years 1 and 1000.
____ Import succeeded.
____ Coordinates imported in the HadCM3DS dataset.
__ Importing temperature.
____ Coordinate imported in the GeoDataArray instance.
____ Processing longitude: weighted_mean
____ Processing latitude: weighted_mean
____ Processing zb: weighted_mean
None; None
None; None
None; None
None; None
None; None
None; None
None; None
None; None
None; None
t: [0001-06-01 00:00:00; 0002-06-01 00:00:00; ...; 0999-06-01 00:00:00; 1000-06-01 00:00:00; 1000]
DATA: <xarray.DataArray (t: 1000)>
array([-0.02729844, -0.02551083, -0.02470834, -0.02328337, -0.02403794,
       -0.02558553, -0.02625738, -0.02711709, -0.02850929, -0.0280898 ,
       -0.02698267, -0.02663598, -0.02861474, -0.0283627 , -0.02790917,
       -0.028847  , -0.02934941, -0.02846134, -0.02894495, -0.02853865,
       -0.02908074, -0.02976845, -0.02976993, -0.03015542, -0.03146428,
       -0.03131

/nfs/see-fs-01_users/eeymr/.conda/envs/eeymr/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [8]:
start = time.time()
ds = hcm3.OCNYDS("xoupb", 1001, 2001)
temperature = ds.temperature(mode_lat="weighted_mean", mode_lon="weighted_mean", mode_z="weighted_mean")
print(temperature)
print(temperature.values())
print(f"Without chunks : {time.time() - start}")

__ Importing <class 'pylaeoclim_leeds.hadcm3_processing.OCNYDS'>
____ Paths generated for xoupb between years 1001 and 2001.
____ Import succeeded.
____ Coordinates imported in the HadCM3DS dataset.
__ Importing temperature.
____ Coordinate imported in the GeoDataArray instance.
____ Processing longitude: weighted_mean
____ Processing latitude: weighted_mean
____ Processing zb: weighted_mean
None; None
None; None
None; None
None; None
None; None
None; None
None; None
None; None
None; None
t: [1001-06-01 00:00:00; 1002-06-01 00:00:00; ...; 2000-06-01 00:00:00; 2001-06-01 00:00:00; 1001]
DATA: <xarray.DataArray (t: 1001)>
array([-0.09249331, -0.09381049, -0.09477145, ...,  0.24236018,
        0.24213456,  0.24111019])
Coordinates:
  * t        (t) object 1001-06-01 00:00:00 ... 2001-06-01 00:00:00
[-0.09249331 -0.09381049 -0.09477145 ...  0.24236018  0.24213456
  0.24111019]
Without chunks : 176.47467827796936


/nfs/see-fs-01_users/eeymr/.conda/envs/eeymr/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [9]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceantemppg01.annual.nc")
print(f"Opening Dataset : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(2000, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Opening Dataset : 0.037079811096191406
Where : 42.25572872161865
Values : 0.00030684471130371094


<xarray.Dataset>
Dimensions:       (depth_1: 1, latitude: 144, longitude: 288, t: 3463)
Coordinates:
  * depth_1       (depth_1) float32 5.0
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 2000-06-01 00:00:00 ... 5462-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 nan nan ... nan nan
Attributes:
    history:                   Thu Dec  3 01:08:37 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

In [10]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceantemppg01.annual.nc", chunks={"t": 1000})
print(f"Time elapsed : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(2000, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Time elapsed : 0.03548550605773926
Where : 0.009498119354248047
Values : 2.5207324028015137


<xarray.Dataset>
Dimensions:       (depth_1: 1, latitude: 144, longitude: 288, t: 3463)
Coordinates:
  * depth_1       (depth_1) float32 5.0
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 2000-06-01 00:00:00 ... 5462-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 dask.array<chunksize=(1, 1, 144, 288), meta=np.ndarray>
Attributes:
    history:                   Thu Dec  3 01:08:37 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

In [11]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xosfy/time_series/xosfy.oceantemppg.annual.nc")
print(f"Opening Dataset : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(100, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Opening Dataset : 0.009143829345703125
Where : 2.907909393310547
Values : 0.001651763916015625


<xarray.Dataset>
Dimensions:       (depth_1: 20, latitude: 144, longitude: 288, t: 99)
Coordinates:
  * depth_1       (depth_1) float32 5.0 15.0 25.0 ... 3961.9 4577.15 5192.45
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 0101-06-01 00:00:00 ... 0199-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 nan nan ... nan nan
Attributes:
    history:                   Fri May 29 01:09:12 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

In [15]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xosfy/time_series/xosfy.oceantemppg.annual.nc", chunks={"t": 50})
print(f"Time elapsed : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(100, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Time elapsed : 0.009769916534423828
Where : 0.004930019378662109
Values : 17.30335521697998


<xarray.Dataset>
Dimensions:       (depth_1: 20, latitude: 144, longitude: 288, t: 99)
Coordinates:
  * depth_1       (depth_1) float32 5.0 15.0 25.0 ... 3961.9 4577.15 5192.45
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 0101-06-01 00:00:00 ... 0199-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 dask.array<chunksize=(50, 20, 144, 288), meta=np.ndarray>
Attributes:
    history:                   Fri May 29 01:09:12 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

In [19]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceantemppg.annual.nc")
print(f"Opening Dataset : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(1000, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Opening Dataset : 0.058425188064575195
Where : 179.52714681625366
Values : 0.07681894302368164


<xarray.Dataset>
Dimensions:       (depth_1: 20, latitude: 144, longitude: 288, t: 4462)
Coordinates:
  * depth_1       (depth_1) float32 5.0 15.0 25.0 ... 3961.9 4577.15 5192.45
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 1001-06-01 00:00:00 ... 5462-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 nan nan ... nan nan
Attributes:
    history:                   Thu Dec  3 01:31:46 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

In [18]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceantemppg.annual.nc", chunks={"t": 1000})
print(f"Time elapsed : {time.time() - start}")
start = time.time()
ts = ts.where(ts.t >= cftime.Datetime360Day(1000, 1, 1), drop=True)
print(f"Where : {time.time() - start}")
start = time.time()
values = ts.temp_ym_dpth.values
print(f"Values : {time.time() - start}")
ts

Time elapsed : 0.044547080993652344
Where : 0.009709835052490234
Values : 345.12931513786316


<xarray.Dataset>
Dimensions:       (depth_1: 20, latitude: 144, longitude: 288, t: 4462)
Coordinates:
  * depth_1       (depth_1) float32 5.0 15.0 25.0 ... 3961.9 4577.15 5192.45
  * latitude      (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude     (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t             (t) object 1001-06-01 00:00:00 ... 5462-06-01 00:00:00
Data variables:
    temp_ym_dpth  (t, depth_1, latitude, longitude) float32 dask.array<chunksize=(1000, 20, 144, 288), meta=np.ndarray>
Attributes:
    history:                   Thu Dec  3 01:31:46 2020: ncrcat -O --no_tmp_f...
    NCO:                       "4.6.1"
    nco_openmp_thread_number:  1

! Carrefull: seems to be very slow as well to access values of bigger dataset such as oceantemppg

## Opening netcdf4

**Idea**: xarray can get very slow to open a netcdf file, especially if it is a large one. This is not necessary to get some simple information such as the first year of the simulation. Using netCDF4 package?

*example* getting the first year of a netCDF time series with xarray:

In [16]:
start = time.time()
ts = xr.open_dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceansalipg16.annual.nc")
print(ts.t.values[0].year)
print(f"Xarray : {time.time() - start}")

1001
Xarray : 0.03322792053222656


In [17]:
start = time.time()
times = netCDF4.Dataset("/nfs/see-fs-01_users/eeymr/database/xoupb/time_series/xoupb.oceansalipg16.annual.nc").variables['t']
print(netCDF4.num2date(times[:],units=times.units,calendar=times.calendar)[0].year)
print(f"Xarray : {time.time() - start}")

1001
Xarray : 0.02283000946044922


## Cropping time series

**Idea**: I should not perform the cropping operations of HadCM3TS every time I open it. If the start or end year have not be changed, it should skip to the next operation.

In [7]:
ts = hcm3.SSTMTS('xoupb',2000)
ts

2000 5462
__ Importation of <class 'pylaeoclim_leeds.hadcm3_processing.SSTMTS'> : xoupb between years 2000 and 5462.
Time elapsed for open_dataset : 0.29164695739746094
Time elapsed for crop start year : 23.835025548934937
Time elapsed for crop start and end years : 24.0935697555542
Time elapsed for crop start and end years and months : 24.09363603591919
____ Import succeeded.
____ Coordinates imported in the HadCM3DS dataset.


lon: [0.0; 1.25; ...; 357.5; 358.75; 288]; lon_p: [0.0; 1.25; ...; 358.75; 360.0; 289]
lonb: [-0.625; 0.625; ...; 358.125; 359.375; 289]; lonb_p: [-0.625; 0.625; ...; 359.375; 360.625; 290]
lons: [1.25; 1.25; ...; 1.25; 1.25; 288]; lons_p: [1.25; 1.25; ...; 1.25; 1.25; 289]
lat: [-89.375; -88.125; ...; 88.125; 89.375; 144]; lat_p: [-89.375; -88.125; ...; 89.375; 90.625; 145]
latb: [-90.0; -88.75; ...; 88.75; 90.0; 145]; latb_p: [-90.0; -88.75; ...; 90.0; 91.25; 146]
lats: [1.25; 1.25; ...; 1.25; 1.25; 144]; lats_p: [1.25; 1.25; ...; 1.25; 1.25; 145]
None; None
None; None
None; None
t: [2000-01-16 00:00:00; 2000-02-16 00:00:00; ...; 5462-11-16 00:00:00; 5462-12-16 00:00:00; 41556]
DATA: <xarray.Dataset>
Dimensions:      (latitude: 144, longitude: 288, t: 41556, unspecified: 1)
Coordinates:
  * latitude     (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude    (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t            (t) object 2000-01-16 00:0

In [8]:
start = time.time()
sst= ts.sst(mode_t="mean")
print(sst.values())
print(f"SST : {time.time() - start}")

__ Importing SST.
____ Coordinate imported in the GeoDataArray instance.
[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]]
SST : 35.18794298171997


/nfs/see-fs-01_users/eeymr/.conda/envs/eeymr/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [12]:
ts = hcm3.SSTMTS('xoupb',2000, chunks=1000)
ts

2000 5462
__ Importation of <class 'pylaeoclim_leeds.hadcm3_processing.SSTMTS'> : xoupb between years 2000 and 5462.
Time elapsed for open_dataset : 0.3210151195526123
Time elapsed for crop start year : 0.3596639633178711
Time elapsed for crop start and end years : 0.630399227142334
Time elapsed for crop start and end years and months : 0.630474328994751
____ Import succeeded.
____ Coordinates imported in the HadCM3DS dataset.


lon: [0.0; 1.25; ...; 357.5; 358.75; 288]; lon_p: [0.0; 1.25; ...; 358.75; 360.0; 289]
lonb: [-0.625; 0.625; ...; 358.125; 359.375; 289]; lonb_p: [-0.625; 0.625; ...; 359.375; 360.625; 290]
lons: [1.25; 1.25; ...; 1.25; 1.25; 288]; lons_p: [1.25; 1.25; ...; 1.25; 1.25; 289]
lat: [-89.375; -88.125; ...; 88.125; 89.375; 144]; lat_p: [-89.375; -88.125; ...; 89.375; 90.625; 145]
latb: [-90.0; -88.75; ...; 88.75; 90.0; 145]; latb_p: [-90.0; -88.75; ...; 90.0; 91.25; 146]
lats: [1.25; 1.25; ...; 1.25; 1.25; 144]; lats_p: [1.25; 1.25; ...; 1.25; 1.25; 145]
None; None
None; None
None; None
t: [2000-01-16 00:00:00; 2000-02-16 00:00:00; ...; 5462-11-16 00:00:00; 5462-12-16 00:00:00; 41556]
DATA: <xarray.Dataset>
Dimensions:      (latitude: 144, longitude: 288, t: 41556, unspecified: 1)
Coordinates:
  * latitude     (latitude) float32 -89.375 -88.125 -86.875 ... 88.125 89.375
  * longitude    (longitude) float32 0.0 1.25 2.5 3.75 ... 356.25 357.5 358.75
  * t            (t) object 2000-01-16 00:0

In [9]:
start = time.time()
sst= ts.sst(mode_t="mean")
print(sst.values())
print(f"SST : {time.time() - start}")

__ Importing SST.
____ Coordinate imported in the GeoDataArray instance.
[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]
 [-1.6763306 -1.6766549 -1.6769887 ... -1.6756562 -1.6759859 -1.6763306]]
SST : 34.734419107437134


In [13]:
# It is weird, it seems that the data is not chunked. To boulbe check. Still a massive improvement!